version: '3.6'
services:
  books:
    container_name: book
    build: ../
    depends_on:
      - postgres
      - redis
    ports:
      - '3000:3000'
    environment:
      PG_USER: 'demo'
      PG_PASSWORD: 'demo'
      PG_HOST: 'localhost'
      PG_PORT: '5432'
      REDIS_UNAME: ''
      REDIS_PORT: '6379'
      REDIS_HOST: 'host.docker.internal'
      REDIS_PASS: ''
  postgres:
    container_name: pg
    image: $PG_IMAGE
    restart: always
    ports:
      - '$PG_PORT:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASSWORD
  redis:
    container_name: redis
    image: $REDIS_IMAGE
    ports:
      - '6379:6379'
    restart: always
    environment:
      # - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'redis_data:/bitnami/redis/data'
volumes:
  db_data:
  redis_data:
    driver: local